openapi: 3.0.3
info:
  title: History Management APIs
  description: APIs for Voter History management
  version: 1.0.0

servers:
  - url: http://localhost:8081/api

paths:
  /history/name/{voterId}:
    get:
      summary: Get Name History by Voter Id
      operationId: nameHistory
      tags:
        - history
      parameters:
        - name: voterId
          in: path
          required: true
          description: Unique ID of the Voter
          schema:
            type: integer
            format: int64
            example: 000000001
      responses:
        "200":
          description: Name History retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoryDTO"
        "404":
          description: Voter not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /history/status/{voterId}:
    get:
      summary: Get Status History by Voter Id
      operationId: statusHistory
      tags:
        - history
      parameters:
        - name: voterId
          in: path
          required: true
          description: Unique ID of the Voter
          schema:
            type: integer
            format: int64
            example: 000000001
      responses:
        "200":
          description: Status History retrieved successfully
          content:
            application/json:
              schema:
                $ref: "./schemas/HistoryDTO.yaml"
        "404":
          description: Voter not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    HistoryDTO:
      $ref: './schemas/historyDTO.yaml'

    ErrorResponse:
      $ref: 'schemas/errorResponse.yaml'