openapi: 3.0.3
info:
  title: Election Related API
  version: 1.0.0
servers:
  -url: http://localhost:8082/api
paths:
  /election:
    get:
      summary: Get all Elections
      operationId: getAllDetails
      tags:
        - Election
      response:
        "200"