# # Use OpenJDK 17 as the base image
# FROM openjdk:23-jdk-slim
#
# # Set the working directory in the container
# WORKDIR /app
#
# # Copy the jar file into the container
# COPY target/election-management-system.jar app.jar
#
# # Expose the port your Spring Boot application runs on
# EXPOSE 8082
#
# # Command to run the application
# ENTRYPOINT ["java", "-jar", "app.jar"]
