version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: kashyap@123
      MYSQL_DATABASE: EMS
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: ems_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/EMS
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kashyap@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    ports:
      - "8080:8081"
    depends_on:
      - mysql
 