#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8
#    container_name: my-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3307:3306"
#    networks:
#      - springboot-mysql-network
#
#  app:
#    build: .
#    container_name: springboot-app
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8082:8082"
#    networks:
#      - springboot-mysql-network
#
#networks:
#  springboot-mysql-network:
#    driver: bridge
